version: '2'
services:
  # oss
  oss:
    image: platzi/oss
    container_name: platzi-oss
    ports:
      - 9696:8000
    networks:
      platzi:
        aliases:
          - platzi-oss
networks:
   platzi:
     external: true
